export const content = {
  nav: [
    ["Galeri", "#work"], ["Neler Yapıyorum?", "#services"], ["Showreel", "#showreel"],
    ["Bayram", "#about"], ["İletişim", "#contact"],
  ],
  hero: {
    kicker: "FİLM · ANİMASYON · POST-PRODÜKSİYON",
    title: "İşiniz", titleItalic: "ekranda.",
    body: "Reklam ve tanıtım filmleri, animasyonlar ve ekran içerikleri hazırlıyorum. Bazen bir ürünün nasıl çalıştığını anlatmak, bazen de bir fikri filme dönüştürmek için.",
    action: "İşleri İnceleyin",
  },
  selected: { kicker: "GALERİ", title: ["Çalışmalardan", "örnekler."], body: "Filmler, animasyonlar ve farklı ekranlar için hazırladığım içerikler. İlgilendiğiniz çalışmayı açıp inceleyebilirsiniz." },
  works: [
    { id: "reklam-packshot", poster: "portrait.jpg", title: "Packshot Serisi", sub: "Kurgu · Hareketli grafik · Ürün çekimi", category: "urun-gorsellestirme", categoryLabel: "ÜRÜN GÖRSELLEŞTİRME", kind: "video", video: "/videos/reklam-packshot.mp4", width: 900, height: 1200, layout: "work-wide", description: "Ürün çekimi ve packshot kurgusu. Kısa versiyonlar teslim edildi." },
    { id: "urun-otomotiv", poster: "car.jpg", title: "Otomotiv Tanıtımı", sub: "3D · Animasyon", category: "reklam", categoryLabel: "REKLAM FİLMİ", kind: "video", video: "/videos/urun-otomotiv.mp4", width: 1920, height: 1080, layout: "work-wide", description: "Stüdyo ışık kurulumu ve 3D destekli tanıtım filmi." },
    { id: "fuar-balina", poster: "whale.jpg", title: "Fuar LED — Balina", sub: "Geniş ve çoklu ekran", category: "fuar-lansman", categoryLabel: "FUAR VE LANSMAN FİLMİ", kind: "gallery", video: "/videos/fuar-balina.mp4", width: 1920, height: 800, layout: "work-xwide", description: "Fuar holündeki 24 metrelik LED duvar için sualtı sahnesi. Üç perde tek akışta birleşir.", gallery: [
      { src: "whale.jpg", caption: "Ana perde — balinanın geçiş anı, 12 sn döngü." },
      { src: "green-city.jpg", caption: "Yan perde — şehir dokusu, renk paleti eşlemesi." },
      { src: "moon-city.jpg", caption: "Gece modu — düşük ışık versiyonu." },
    ] },
    { id: "metro-ay-sehri", poster: "moon-city.jpg", title: "Metro Ekranı — Ay Şehri", sub: "LED · Metro · AVM", category: "acik-hava", categoryLabel: "AÇIK HAVA VİDEOSU", kind: "video", video: "/videos/metro-ay-sehri.mp4", width: 720, height: 1280, layout: "work-tall", description: "Metro peronlarındaki dikey ekranlar için 15 sn sessiz döngü." },
    { id: "avm-yesil-sehir", poster: "green-city.jpg", title: "AVM LED — Yeşil Şehir", sub: "Kurgu · Grafik · Görsel efekt", category: "acik-hava", categoryLabel: "AÇIK HAVA VİDEOSU", kind: "gallery", video: "/videos/avm-yesil-sehir.mp4", width: 1920, height: 1080, layout: "work-mid", description: "AVM içindeki tavan ekranı için hazırlanan görüntüler. Sabah, öğle ve akşam için farklı versiyonlar.", gallery: [
      { src: "green-city.jpg", caption: "Gündüz bandı — tavan LED, 20 sn." },
      { src: "car.jpg", caption: "Referans kare — renk ve kontrast ayarı." },
    ] },
    { id: "motion-kurdele", poster: "ribbons.jpg", title: "Kurdele Anlatımı", sub: "Grafik anlatım · Jenerik", category: "urun-gorsellestirme", categoryLabel: "GRAFİK İÇERİK", kind: "video", video: "/videos/motion-kurdele.mp4", width: 1080, height: 1080, layout: "work-mid", description: "Bir etkinliğin açılışı için kare formatta hazırlanan animasyon." },
    { id: "sosyal-parfum", poster: "perfume.jpg", title: "Parfüm — Kısa Format", sub: "Sosyal medya · Dikey video", category: "sosyal", categoryLabel: "SOSYAL MEDYA VİDEOSU", kind: "video", video: "/videos/sosyal-parfum.mp4", width: 1080, height: 1350, layout: "work-mid", description: "Sosyal medya için dikey video. Ürün, filmin ilk saniyelerinde öne çıkıyor." },
    { id: "tanitim-ornek", detailOnly: true, poster: "car.jpg", title: "Tanıtım Filmi — Örnek Görsel", sub: "Örnek görseller", category: "tanitim", categoryLabel: "ÜRÜN, HİZMET VE ŞİRKET TANITIMI", kind: "gallery", width: 1920, height: 1080, description: "Bu bölümdeki görseller geçicidir; tamamlanmış bir tanıtım projesini göstermez.", gallery: [{ src: "car.jpg" }, { src: "car.jpg" }, { src: "ribbons.jpg" }] },
    { id: "medikal-ornek", detailOnly: true, poster: "ribbons.jpg", title: "Medikal Anlatım — Örnek Görsel", sub: "Örnek görseller", category: "medikal", categoryLabel: "MEDİKAL FİLM VE ANİMASYON", kind: "gallery", width: 1080, height: 1080, description: "Bu bölümdeki görseller geçicidir; tamamlanmış bir medikal projeyi göstermez.", gallery: [{ src: "ribbons.jpg" }, { src: "ribbons.jpg" }, { src: "green-city.jpg" }] },
  ],
  galleryTabs: [
    { category: "reklam", label: "REKLAM FİLMLERİ", full: "REKLAM FİLMLERİ" },
    { category: "sosyal", label: "SOSYAL MEDYA", full: "SOSYAL MEDYA VİDEOLARI" },
    { category: "tanitim", label: "TANITIMLAR", full: "ÜRÜN, HİZMET VE ŞİRKET TANITIMLARI" },
    { category: "medikal", label: "MEDİKAL", full: "MEDİKAL FİLM VE ANİMASYONLAR" },
    { category: "acik-hava", label: "AÇIK HAVA", full: "AÇIK HAVA VE DİJİTAL EKRAN FİLMLERİ" },
    { category: "fuar-lansman", label: "FUAR · LANSMAN", full: "FUAR VE LANSMAN FİLMLERİ" },
    { category: "urun-gorsellestirme", label: "GÖRSELLEŞTİRME", full: "ÜRÜN GÖRSELLEŞTİRME VE GRAFİK İÇERİKLER" },
  ],
  services: [
    ["kurgu-gorsel-anlatim.png", "Kurgu", "Görüntü, ses ve filmin akışı"],
    ["motion-graphics.png", "Hareketli Grafik", "Yazı, grafik ve animasyon"],
    ["3d-cgi.png", "3D Görselleştirme", "Ürün, mekân ve dijital sahneler"],
    ["compositing-vfx.png", "Görsel Efekt", "Çekim ve dijital görüntüleri birleştirme"],
    ["ai-gorsel-uretim.png", "Yapay Zekâ ile Görsel Üretim", "Görsel denemeler ve sahne üretimi"],
    ["color-tracking.png", "Renk ve Kamera Takibi", "Renk düzenleme ve görüntüye öğe ekleme"],
    ["senaryo-produksiyon.png", "Senaryo ve Çekim", "Fikirden senaryoya, senaryodan çekime"],
  ],
  servicePanels: [
    { body: "Çekilen görüntüleri seçip sıralıyor, ses ve müzikle birlikte kurguluyorum. Filmin süresini ve temposunu anlatılacak konuya ve gösterileceği yere göre düzenliyorum.", examples: ["reklam-packshot", "urun-otomotiv"] },
    { body: "Yazıları, çizimleri ve grafikleri canlandırıyorum. Bir ürünün özelliklerini anlatan animasyonlar, jenerikler ve sosyal medya içerikleri hazırlıyorum.", examples: ["motion-kurdele", "sosyal-parfum"] },
    { body: "Ürün ve mekânları üç boyutlu olarak modelliyor, ışık ve malzemelerini hazırlıyorum. Çekimle gösterilmesi zor ayrıntıları ve hareketleri de bu şekilde anlatabiliyorum.", examples: ["reklam-packshot", "urun-otomotiv"] },
    { body: "Çekilmiş görüntülere 3D öğeler ve grafikler ekliyor, ayrı görüntüleri birleştiriyorum. Eklenen parçaların ışığını, rengini ve gölgesini çekimle uyumlu olacak şekilde düzenliyorum.", examples: ["avm-yesil-sehir", "metro-ay-sehri"] },
    { body: "Yapay zekâyı görsel fikirleri denemek, sahne ve efekt üretmek için kullanıyorum. Çıkan görüntüleri kurgu, renk ve görsel efekt çalışmasıyla filme uyarlıyorum.", examples: ["reklam-packshot", "motion-kurdele"] },
    { body: "Farklı çekimler arasındaki renk ve ışık farklarını düzenliyorum. Kamera takibiyle de sonradan eklenen yazı ve nesnelerin görüntüdeki hareketi izlemesini sağlıyorum.", examples: ["sosyal-parfum", "fuar-balina"] },
    { body: "Anlatmak istediğiniz konuyu senaryoya dönüştürüyorum. Çekim gereken işlerde ekibi oluşturuyor, hazırlık ve çekim sürecini yönetiyorum.", examples: ["reklam-packshot", "urun-otomotiv"] },
  ],
  showreel: {
    youtubeId: "7J-6jXEM6ao",
    sideBrand: "MISAL WORKS",
    sideTitle: "Showreel",
    sideBody: "Farklı çalışmalardan bölümleri bu videoda bir araya getirdim.",
    sideMeta: ["Reklam filmleri", "3D ve animasyon", "Kurgu ve görsel efekt"],
    kicker: "SHOWREEL", title: "Kısa bir\nbakış.",
    body: "Filmlerden ve animasyonlardan bölümler.\nÇalışmaları hareketi ve sesiyle izleyin.",
    watch: ["SHOWREEL'İ", "İZLE"],
  },
  philosophy: {
    kicker: "BAYRAM ŞİMŞEKOĞLU", title: "Merhaba,\nben Bayram.",
    lead: "Misal Works adıyla film, animasyon ve post-prodüksiyon işleri yapıyorum. Projenizi benimle konuşuyor, süreç boyunca doğrudan benimle çalışıyorsunuz. Kurgu, animasyon ve görsel üretimi üstleniyorum. Çekim ya da başka bir uzmanlık gerektiğinde ekibi işe göre oluşturuyorum.",
    chapters: [
      ["BAŞLANGIÇ", "Önce ne anlatmak istediğinizi ve filmin nerede kullanılacağını konuşuyoruz. Elinizde bir senaryo, birkaç referans ya da yalnızca bir fikir olabilir. Nereden başlayacağımızı bunlara bakarak belirliyoruz."],
      ["YÖNTEM", "Bazı işler çekim ister, bazılarında animasyon daha iyi sonuç verir. Elinizde kullanılabilecek görüntüler varsa onlarla da çalışabiliriz. Yöntemi, anlatılacak konuya göre seçiyorum."],
      ["BİRLİKTE ÇALIŞMA", "İşi konuştuğunuz kişiyle işi hazırlayan kişi aynı. Ne istediğinizi doğrudan bana anlatabilir, çalışma hakkındaki görüşlerinizi benimle paylaşabilirsiniz."],
      ["EKİP", "Çekim ya da ek uzmanlık gerektiğinde birlikte çalışacağım kişileri projeye göre belirliyorum. Ekibin yaptığı işi de takip ediyor, filmin diğer parçalarıyla bir araya getiriyorum."],
      ["TESLİM", "Sosyal medyadaki bir video ile fuar ekranındaki bir film aynı biçimde hazırlanmıyor. Süreyi, kadrajı ve ekran ölçülerini baştan konuşup son dosyaları kullanılacakları yere göre düzenliyorum."],
    ],
  },
  servicesIntro: {
    kicker: "ÇALIŞMA ALANLARI", title: "Neler\nyapıyorum?",
    body: "Bir filmin tamamını ya da yalnızca\nkurgu, animasyon ve görsel efektini üstlenebilirim.", action: "PROJENİZİ KONUŞALIM",
  },
  footer: {
    title: "Aklınızda nasıl\nbir proje var?",
    message: "Projenizi konuşmak için arayabilir veya e-posta gönderebilirsiniz.", action: "E-posta Gönderin",
    phone: "+90 (216) 599 0134",
    phoneHref: "tel:+902165990134",
    email: "hello@misalworks.com",
    location: "Justwork",
    address: "Fatih Sultan Mehmet Mah., Balkan Cad., JUSTWork Ofis Kampüs, No:62A, 34770 Ümraniye / İstanbul",
  },
};
