export const content = {
  nav: [
    ["İşler", "#work"], ["İş Türleri", "#services"], ["Showreel", "#showreel"],
    ["Bayram", "#about"], ["İletişim", "#contact"],
  ],
  hero: {
    kicker: "REKLAM · ÜRÜN · AÇIK HAVA · EKRAN",
    title: "İşiniz", titleItalic: "ekranda.",
    body: "Reklam filmleri, ürün tanıtımları, açık hava videoları ve farklı ekranlar için içerikler üretiyorum. Kurgu, motion graphics, 3D ve görsel efekti işin ihtiyacına göre bir araya getiriyorum.",
    action: "İşleri İnceleyin",
  },
  selected: { kicker: "ÇALIŞMALAR", title: ["Yaptığım çalışmalardan", "örnekler."], action: "ÇALIŞMA ALANLARI", body: "Yaptığım çalışmalardan örnekler." },
  works: [
    { id: "reklam-packshot", poster: "portrait.jpg", title: "Packshot Serisi", sub: "Kurgu · Motion graphics · Packshot", category: "reklam", categoryLabel: "REKLAM FİLMİ", kind: "video", video: "/videos/reklam-packshot.mp4", width: 900, height: 1200, layout: "work-wide", description: "Ürün çekimi ve packshot kurgusu. Kısa versiyonlar teslim edildi." },
    { id: "urun-otomotiv", poster: "car.jpg", title: "Otomotiv Tanıtımı", sub: "3D · Animasyon", category: "reklam", categoryLabel: "REKLAM FİLMİ", kind: "video", video: "/videos/urun-otomotiv.mp4", width: 1920, height: 1080, layout: "work-wide", description: "Stüdyo ışık kurulumu ve 3D destekli tanıtım filmi." },
    { id: "fuar-balina", poster: "whale.jpg", title: "Fuar LED — Balina", sub: "Geniş ve çoklu ekran", category: "acik-hava", categoryLabel: "AÇIK HAVA VİDEOSU", kind: "gallery", video: "/videos/fuar-balina.mp4", width: 1920, height: 800, layout: "work-xwide", description: "Fuar holündeki 24 metrelik LED duvar için sualtı sahnesi. Üç perde tek akışta birleşir.", gallery: [
      { src: "whale.jpg", caption: "Ana perde — balinanın geçiş anı, 12 sn döngü." },
      { src: "green-city.jpg", caption: "Yan perde — şehir dokusu, renk paleti eşlemesi." },
      { src: "moon-city.jpg", caption: "Gece modu — düşük ışık versiyonu." },
    ] },
    { id: "metro-ay-sehri", poster: "moon-city.jpg", title: "Metro Ekranı — Ay Şehri", sub: "LED · Metro · AVM", category: "acik-hava", categoryLabel: "AÇIK HAVA VİDEOSU", kind: "video", video: "/videos/metro-ay-sehri.mp4", width: 720, height: 1280, layout: "work-tall", description: "Metro peronlarındaki dikey ekranlar için 15 sn sessiz döngü." },
    { id: "avm-yesil-sehir", poster: "green-city.jpg", title: "AVM LED — Yeşil Şehir", sub: "Kurgu · Grafik · Compositing", category: "acik-hava", categoryLabel: "AÇIK HAVA VİDEOSU", kind: "gallery", video: "/videos/avm-yesil-sehir.mp4", width: 1920, height: 1080, layout: "work-mid", description: "AVM atrium tavan bandı için gün döngüsü. Sabah, öğle ve akşam versiyonları.", gallery: [
      { src: "green-city.jpg", caption: "Gündüz bandı — tavan LED, 20 sn." },
      { src: "car.jpg", caption: "Referans kare — renk ve kontrast ayarı." },
    ] },
    { id: "motion-kurdele", poster: "ribbons.jpg", title: "Kurdele Anlatımı", sub: "Grafik anlatım · Jenerik", category: "motion-sosyal", categoryLabel: "MOTION GRAPHICS", kind: "video", video: "/videos/motion-kurdele.mp4", width: 1080, height: 1080, layout: "work-mid", description: "Etkinlik açılış jeneriği, kare format ana sahne." },
    { id: "sosyal-parfum", poster: "perfume.jpg", title: "Parfüm — Kısa Format", sub: "Kısa format · Versiyonlama", category: "motion-sosyal", categoryLabel: "SOSYAL MEDYA VİDEOSU", kind: "video", video: "/videos/sosyal-parfum.mp4", width: 1080, height: 1350, layout: "work-mid", description: "Dikey kısa format, ilk 2 saniyeye hook kurgusu." },
  ],
  services: [
    ["ReklamFilmleri.png", "Reklam Filmleri", "Marka ve ürün reklamları"],
    ["AcikHavaVidolari_.png", "Açık Hava Videoları", "LED, metro, AVM ve mağaza"],
    ["Urun_tanitimlari.png", "Ürün Tanıtımları", "Özellik ve kullanım filmleri"],
    ["FuarveLansmanVideolari.png", "Fuar ve Lansman", "Etkinlik ve geniş ekran"],
    ["MedikaAnimasyonalr.png", "Medikal Animasyon", "Etki ve ürün anlatımları"],
    ["UrunGorsellestirme.png", "Ürün Görselleştirme", "3D model, render ve packshot"],
    ["SosyalMedya.png", "Sosyal Medya", "Reklam ve tanıtım videoları"],
  ],
  servicePanels: [
    { body: "Reklam filmleri yapıyoruz. Fikirden yayına konsept, çekim, kurgu ve post-prodüksiyonu tek elden yürütüyoruz.", examples: ["reklam-packshot", "urun-otomotiv"] },
    { body: "Açık hava videoları üretiyoruz. LED, metro, AVM ve mağaza ekranlarına özel format ve sürelerde çalışıyoruz.", examples: ["metro-ay-sehri", "avm-yesil-sehir", "fuar-balina"] },
    { body: "Ürün tanıtımları yapıyoruz. Özellik ve kullanım filmlerini ürünün en güçlü yanını öne çıkaracak şekilde kurguluyoruz.", examples: ["urun-otomotiv", "sosyal-parfum"] },
    { body: "Fuar ve lansman filmleri hazırlıyoruz. Etkinlik ve geniş ekranlara özel yüksek etkili açılış içerikleri üretiyoruz.", examples: ["fuar-balina", "metro-ay-sehri"] },
    { body: "Medikal animasyonlar yapıyoruz. Etki ve ürün anlatımlarını bilimsel doğrulukla, anlaşılır görsellikle sunuyoruz.", examples: ["motion-kurdele", "avm-yesil-sehir"] },
    { body: "Ürün görselleştirme yapıyoruz. 3D model, render ve packshot ile ürünü en iyi ışığında gösteriyoruz.", examples: ["reklam-packshot", "urun-otomotiv", "sosyal-parfum"] },
    { body: "Sosyal medya videoları üretiyoruz. Reklam ve tanıtım için dikey ve kısa formatlara özel içerikler hazırlıyoruz.", examples: ["sosyal-parfum", "motion-kurdele"] },
  ],
  showreel: {
    youtubeId: "7J-6jXEM6ao",
    sideBrand: "MISAL WORKS",
    sideTitle: "Showreel",
    sideBody: "Son işlerden kısa bir seçki. Tek tıkla başlar.",
    sideMeta: ["Süre: yaklaşık 1 dakika", "Reklam · 3D · Motion · VFX", "2024–2026 seçki"],
    kicker: "SHOWREEL", title: "İşler hareket\nhalinde.",
    body: "Reklam, 3D, motion graphics ve post-prodüksiyon\nçalışmalarından kısa bir seçki.",
    watch: ["SHOWREEL'İ", "İZLE"], script: ["KURGU", "3D", "VFX"],
  },
  philosophy: {
    kicker: "BAYRAM ŞİMŞEKOĞLU", title: "Misal'in arkasında\nkim var?",
    lead: "Misal Works'ün arkasında Bayram Şimşekoğlu var. 25 yılı aşkın post-prodüksiyon deneyimimle her işle doğrudan ilgileniyorum. Çekim ya da ek uzmanlık gerektiğinde doğru ekibi kurup süreci yönetiyorum. Kurgudan renk düzenlemeye, motion graphics'ten 3D'ye kadar sürecin her adımını tek elden yürütüyor, fikrin ilk taslağından teslim edilen master'a kadar aynı özenle çalışıyorum.",
    script: ["25+", "YIL", "DENEYİM"],
    chapters: [
      ["KURGU", "Kurgu bir işin ritmini kurar. Ham görüntüyü izleyicinin dikkatini canlı tutacak biçimde düzenler, gereksiz olanı keser, kalanı güçlendirir. Reklam, tanıtım ve sosyal medya formatlarında anlatının akışını, tempoyu ve süreyi birlikte tasarlarım."],
      ["MOTION GRAPHICS", "Hareket, sabit görselin anlatamadığını söyler. Tipografi, geçiş, ikon ve grafik katmanlarını markanın diliyle uyumlu biçimde canlandırırım. Amaç gösteriş değil; bilgiyi daha anlaşılır ve akılda kalıcı kılmak."],
      ["3D", "Ürün, mekân ya da soyut form; 3D ile anlatılan her şey inandırıcı olmalı. Modelleme, malzeme, ışık ve render aşamalarını tek akışta yürütür, görselleştirmeyi çekimle aynı kalitede bütünleştiririm."],
      ["COMPOSITING", "Compositing, ayrı ayrı üretilen katmanları tek bir gerçekliğe dönüştürür. Yeşil perde, 3D çıktıları ve çekim görüntülerini renk, ışık ve gölge tutarlılığı içinde birleştirir; sahnelerin kusursuz görünmesini sağlarım."],
      ["TRACKING", "Kamera takibi, dijital varlıkları gerçek çekime oturtur. Hareketli kamera, perspektif ve plan kaymalarını izleyerek eklenen öğelerin sahnede doğmuş gibi durmasını sağlarım."],
    ],
  },
  servicesIntro: {
    kicker: "ÇALIŞMA ALANLARI", title: "Hangi iş için\ngeldiniz?",
    body: "Reklamdan açık havaya, ürün görselleştirmeden\nmedikal animasyona.", action: "İŞİNİZİ ANLATIN",
  },
  footer: {
    title: "Elinizde nasıl\nbir iş var?",
    message: "Ne anlatmak istediğinizi, filmin nerede kullanılacağını\nve varsa teslim tarihini yazın.", action: "İşinizi Anlatın",
  },
};
